# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Aplade
tagline:             'Capital Markets Technology Consulting Services'
description:         ''
url:                 http://www.aplade.com
baseurl:             
paginate:            5
markdown: kramdown


gems: [jekyll-paginate]
excerpt_separator: "\n\n"

# About/contact
author:
  gravatar:          d93292f482cdae112e86b557cf69a279
  name:              Roberto Bastianic
  url:               
  email:             roberto.bastianic@gmail.com

# Custom vars
version:             1.0.0
