# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Aplade
tagline:             'Capital Markets Technology Consulting Services'
description:         ''
url:                 http://www.aplade.com
baseurl:             
paginate:            5

gems: [jekyll-paginate]

# About/contact
author:
  name:              Roberto Bastianic
  url:               
  email:             roberto.bastianic@aplade.com

# Custom vars
version:             1.0.0
